version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - fleet-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fleet-network

  sonarqube:
    image: sonarqube:community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/fleetdb
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: password
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - fleet-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:

networks:
  fleet-network:
    driver: bridge