name: CI/CD pipeline

on:
  push:
    branches: [main]
    pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Test
      run: |
        chmod +x mvnw
        ./mvnw clean verify

    - name: Build Docker Image
      run: docker build -t fleet-manager:latest .

    - name: Run SonarQube Analysis
      run: |
        .mvnw sonar:sonar \
          -Dsonar.projectkey=fleet-manager\
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fleet-manager:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy acan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-result.sarif'